{{- if .Values.volume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.name }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  {{- if .Values.volume.storageClassName }}
  storageClassName: {{ .Values.volume.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
{{- end }}
